#!/usr/bin/env bash
# Set up the repository

# Stop on errors
set -e

cd "$(dirname "$0")/.."

if [ ! -n "$VIRTUAL_ENV" ]; then
  if [ -x "$(command -v uv)" ]; then
    uv venv
  else
    python3 -m venv .venv
  fi
  source .venv/bin/activate
fi

if ! [ -x "$(command -v uv)" ]; then
  python3 -m pip install uv
fi

uv sync

pre-commit install
